language: node_js
node_js:
  - "10"

os: linux

matrix:
  include:
    - name: test
      before_install: cd client && yarn
      script:
        - yarn test
    - name: lint
      before_install: cd client && yarn
      script:
        - yarn lint

cache: yarn
